import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  async redirects() {
    return [
      // Blog is parked until real post bodies exist: /blog and every /blog/* URL
      // permanently redirect to the homepage. Content files are kept in src/app/blog.
      {
        source: "/blog/:slug*",
        destination: "/",
        statusCode: 301,
      },
      // The branded icon is generated by src/app/icon.tsx; send legacy /favicon.ico probes there.
      {
        source: "/favicon.ico",
        destination: "/icon",
        statusCode: 301,
      },
    ];
  },
};

export default nextConfig;
