import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  async headers() {
    return [
      {
        // Photos and the hero video change by filename, so they can be cached for a year.
        source: "/:dir(images|videos)/:path*",
        headers: [{ key: "Cache-Control", value: "public, max-age=31536000, immutable" }],
      },
    ];
  },
  async redirects() {
    return [
      // Blog is parked until real post bodies exist: /blog and every /blog/* URL
      // permanently redirect to the homepage. Content files are kept in src/app/blog.
      {
        source: "/blog/:slug*",
        destination: "/",
        statusCode: 301,
      },
      // The branded icon is generated by src/app/icon.tsx; send legacy /favicon.ico probes there.
      {
        source: "/favicon.ico",
        destination: "/icon",
        statusCode: 301,
      },
    ];
  },
};

export default nextConfig;
